### ISSUE TITLE
Client for test_client is missing

### ISSUE THREAD

**Issue by roddyyaga** [mirage/colombe#20]
There is no client for `test_client` to test (it should probably be [this](https://github.com/Julow/colombe/blob/client/client/client.ml)).

**Comment by roddyyaga** [comment]
It would great for this to be fixed by putting something like that client in the library (rather than just deleting `test_client`). Currently there isn't a high-level OCaml email client library that works with lwt and can authenticate to SMTP servers.

**Comment by dinosaure** [comment]
So `sendmail` and `sendmail-lwt` wants to do this job as a library. We probably missed the documentation about `sendmail-lwt` but the API is quite easy:

```ocaml
val sendmail :
  hostname:'a Domain_name.t ->
  ?port:int ->
  domain:Colombe.Domain.t ->
  authenticator:X509.Authenticator.t ->
  ?authentication:Sendmail.authentication ->
  Colombe.Reverse_path.t ->
  Colombe.Forward_path.t list ->
  (unit -> (string * int * int) option Lwt.t) ->
  (unit, error) result Lwt.t
```

It handles authentication and and it was used by [dinosaure/facteur](https://github.com/dinosaure/facteur.git) ([here](https://github.com/dinosaure/facteur/blob/master/bin/sendmail_handler.ml)) to provide a final binary (which does more - it handles file attachments). You probably are interested by that.

If we missed something, let me know :+1: - I will considering this issue as a lack of documentation.

**Comment by dinosaure** [comment]
I put a documentation on `sendmail-lwt` which should be enough to submit an email to a SMTP server (such as gmail). For more details about the purpose of `colombe`, you should look into this little article: https://blog.x25519.net/2020-03-31--release-cycle-email.html.
