### ISSUE TITLE
authentication fails when server reply is missing space after 334 code

### ISSUE THREAD

**Issue by mikonieminen** [mirage/colombe#26]
Colombe throws after trying to start authentication when using ethereal.email service. The same authentication succeeds when using GMail or Mailtrap where you have something like:
```
main.exe: [DEBUG] Clean internal buffer to start TLS.
main.exe: [DEBUG] Start TLS.
main.exe: [DEBUG] <= "EHLO inbox.mailtrap.io\r\n"
main.exe: [DEBUG] => "250-mailtrap.io\r\n250-SIZE 5242880\r\n250-PIPELINING\r\n250-ENHANCEDSTATUSCODES\r\n250-8BITMIME\r\n250-DSN\r\n250 AUTH PLAIN LOGIN CRAM-MD5\r\n"
main.exe: [DEBUG] <= "AUTH PLAIN\r\n"
main.exe: [DEBUG] => "334 \r\n"
```

In ethereal.email you have:
```
main.exe: [DEBUG] Clean internal buffer to start TLS.
main.exe: [DEBUG] Start TLS.
main.exe: [DEBUG] <= "EHLO ethereal.email\r\n"
main.exe: [DEBUG] => "250-smtp.ethereal.email Nice to meet you, 178-83-55-11.dynamic.hispeed.ch\r\n250-PIPELINING\r\n250-8BITMIME\r\n250-SMTPUTF8\r\n250 AUTH LOGIN PLAIN\r\n"
main.exe: [DEBUG] <= "AUTH PLAIN\r\n"
main.exe: [DEBUG] => "334\r\n"
email-test: internal error, uncaught exception:
            (Failure "Sending email failed, Unexpected char: 0d")
```

The issues seems to be that ethereal.email is missing space after 334 code that causes the code to fail as it receives `\r` (0d) while expecting space. Is this bug in Colombe when it fails, if that space is missing or is this bug in ethereal.email service not having it?

**Comment by mikonieminen** [comment]
Looking at [RFC 4954 section 8](https://tools.ietf.org/html/rfc4954#section-8), it seems that the space should be there so this is actually a bug in ethereal.email service.

**Comment by dinosaure** [comment]
Yes, however, we should be more resilient :+1:. So I consider it as a bug of `colombe` and will fix it as soon as possible. Thank for your report!
