### ISSUE TITLE
Allow `AUTH LOGIN` mechanism

### ISSUE THREAD

**Issue by aronerben** [mirage/colombe#60]
Hello, from what I'm seeing currently, only the `AUTH PLAIN` mechanism is supported in `sendmail`. It would be very beneficial for us if `AUTH LOGIN` is also supported, as we are using Microsoft Exchange SMTP servers and [they have disallowed `AUTH PLAIN` back in 2017 apparently](https://support.microsoft.com/en-us/office/outlook-com-no-longer-supports-auth-plain-authentication-07f7d5e9-1697-465f-84d2-4513d4ff0145).

Thank you!

**Comment by mabiede** [comment]
@dinosaure we would very much appreciate it if this would be implemented. Is there any update on this?

**Comment by dinosaure** [comment]
Sorryfor the delay, it's on my TODO list, I will probably try an implementation next week.

**Comment by dinosaure** [comment]
I just dig in into the `LOGIN` method and it seems an _obsolete_ method (only a draft exists about it: https://datatracker.ietf.org/doc/html/draft-murchison-sasl-login-00). I can implement it but do you have another (better) mechanism available?

**Comment by aronerben** [comment]
@dinosaure Thanks a lot for looking into it and drafting a PR! Unfortunately, `AUTH LOGIN` is the only mechanism we can use at the moment. [Outlook.com seems to have discontinued support for `AUTH PLAIN` back in 2017](https://support.microsoft.com/en-us/office/outlook-com-no-longer-supports-auth-plain-authentication-07f7d5e9-1697-465f-84d2-4513d4ff0145) and most of our infrastructure runs on that. So from what I'm seeing, having `AUTH LOGIN` support in our OCaml Apps is unavoidable.

**Comment by dinosaure** [comment]
@aronerben thanks for your reply. I was just wondering if you can use a better mechanism, `LOGIN` seems highly risky to use. Can you try a connection with my draft? Only bad cases are missing but if you use a good username/password, you should able to send an email now with the `LOGIN` mechanism.

**Comment by aronerben** [comment]
@dinosaure I found the problem, I had forgotten to change the mechanism while using STARTTLS :) The happy path works with `LOGIN` on your draft!

**Comment by dinosaure** [comment]
Thanks for you feedback. I will cut a release as soon as I can :+1:. About NTLM mechanism, we probably should make an other issue about that (and when I will have the time, I will try to implement it).

**Comment by aronerben** [comment]
@dinosaure Thanks a bunch for your work :fireworks: , I'll make the issue.
